//
//  BBLErrors.h
//  Framework
//
//  Created by Michael Merickel on 2/23/17.
//  Copyright © 2017 Digital Artefacts LLC. All rights reserved.
//

#import <Foundation/Foundation.h>

NS_ASSUME_NONNULL_BEGIN

/**
 The error domain returned for errors generated by the BrainBaseline library.
 */
extern NSString *const BBLErrorDomain;

/**
 Possible error codes generated by the BrainBaseline library.
 */
typedef NS_ENUM(NSInteger, BBLErrorCode) {
    /**
     The `BBLPsychTestResultID` is unknown in the given `BBLContext`.
     Results are typically only accessible on applications containing the
     `BBLUser` that generated the result.
     */
    kBBLErrorCode_UnknownPsychTestResult = 101,
    
    /**
     The specified psych test could not be run on current device.
     */
    kBBLErrorCode_PsychTestIsNotAvailable = 102,
    
    /**
     The specified psych test could not be found.
     */
    kBBLErrorCode_UnknownPsychTest = 103,
    
    /**
     The `BBLPercentileScore` cannot be computed because the matched
     population does not have enough data to compute a statistically
     significant population distribution.
     */
    kBBLErrorCode_NotEnoughPopulationData = 1001,
    
    /**
     The user cannot be mapped to a valid population. For example,
     if they have not provided a gender, we cannot map them to the appropriate
     gender population.
     */
    kBBLErrorCode_UnknownPopulation = 1003,
};

NS_ASSUME_NONNULL_END
